@ECHO OFF
Color 80
REM This file was generated by 'Prog_Generator_MobaLedLib.xlsm'  15:07:37
REM
REM It updates/installs all required libraries for the MobaLedLib projects.
REM
REM Attention:
REM This program must be started from the arduino libraries directory
REM

CHCP 65001 >NUL

ECHO *******************
ECHO Updating NmraDcc...
ECHO *******************
if EXIST NmraDcc\NUL (
   ECHO deleting old directory NmraDcc\
   rmdir NmraDcc\ /s /q
   timeout /T 3 /nobreak
)
if EXIST NmraDcc\NUL (
   ECHO Error deleting old directory NmraDcc\
   ECHO For some reasons the directory could not be deleted ;-(
   ECHO Check if an other program is active which prevents the deleting
   ECHO of the directory
   ECHO.
   ECHO Going to try a second time
   PAUSE
   rmdir NmraDcc\ /s /q
   timeout /T 3 /nobreak
)
if EXIST NmraDcc\NUL (
   COLOR 4F
   ECHO Error: Still not able to delete the old directory NmraDcc\   ;-(((
   PAUSE
)
powershell Invoke-WebRequest "https://github.com/Jueff/NmraDcc/archive/master.zip" -o:NmraDcc.zip
ECHO Invoke-WebRequest result: %ERRORLEVEL%
IF ERRORLEVEL 1 Goto ErrorMsg
ECHO.

ECHO ************************************
ECHO  Installing the following libraries
ECHO ************************************
ECHO   CAN
ECHO.
@if exist "%USERPROFILE%\AppData\Local\Temp\MobaLedLib_build\ESP32\includes.cache" del "%USERPROFILE%\AppData\Local\Temp\MobaLedLib_build\ESP32\includes.cache"
"C:\Program Files (x86)\Arduino\arduino_debug.exe" --install-library "CAN" 2>&1 | find /v " StatusLogger " | find /v " INFO c.a" | find /v " WARN p.a" | find /v " WARN c.a"
ECHO.
ECHO Error %ERRORLEVEL%
IF ERRORLEVEL 1 Goto ErrorMsg

ECHO *********************************
ECHO  Installing the following boards
ECHO *********************************
ECHO   esp32:esp32:1.0.4
ECHO.
@if exist "%USERPROFILE%\AppData\Local\Temp\MobaLedLib_build\ESP32\includes.cache" del "%USERPROFILE%\AppData\Local\Temp\MobaLedLib_build\ESP32\includes.cache"
"C:\Program Files (x86)\Arduino\arduino_debug.exe" --install-boards esp32:esp32:1.0.4 --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" 2>&1 | find /v " StatusLogger " | find /v " INFO c.a" | find /v " WARN p.a" | find /v " WARN c.a"
ECHO.
ECHO Error %ERRORLEVEL%
IF ERRORLEVEL 1 Goto ErrorMsg

Exit

:ErrorMsg
   COLOR 4F
   ECHO   ****************************************
   ECHO    Da ist was schief gegangen ;-(
   ECHO   ****************************************
   Pause
